#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : STScI  # The title of the book. Will be placed in the left navbar.
author                      : STScI  # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : stsci_logo2.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks         : force   # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : -1    # timeout in seconds, -1 removes timeout restrictions
  only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    
# Define the name of the latex output file for PDF builds
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    
# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
  
launch_buttons:
  thebe                  : true
  binderhub_url: ""

# Information about where the book exists on the web
repository:
  url: https://github.com/spacetelescope/roman_notebooks/  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  google_analytics_id:
  use_issues_button: true
  use_repository_button: true
