on:
  workflow_call:
      secrets:
        CASJOBS_USERID:
          description: 'CASJOBS user ID'
          required: false
        CASJOBS_PW:
          description: 'CASJOBS password'
          required: false
env:
  CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
  CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
  
 
jobs:
  deploy-book:
    ## Only run if the PR is closed and merged
    if: github.event.pull_request.merged == true
    #if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true ))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:  
    - name: Free up disk space
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v4
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v5 ## needed for caching
      with:
        python-version: 3.8.12
        cache: 'pip'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        ## Install the global requirements file - needed for jupyter-book
        pip install -r requirements.txt
        pip install ghp-import
        pip install jupyter-book
        pip install myst-nb
        pip install nbval
        ## work-around to bypass the jupyter-book lower version
        pip install jsonschema==4.6.0
        PATH="${PATH}:${HOME}/.local/bin"
    - name: Build book HTML 
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
